[package]
edition = "2021"
license = "MIT OR Apache"
name = "axum-easy-multipart-derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["derive", "parsing"] }
