[package]
edition = "2021"
license = "AGPL-3.0-or-later"
name = "viewspec"
version = "0.1.0"

[dependencies]
smallvec = { version = "1", features = ["const_generics"] }
thiserror = "1"

[dev-dependencies]
itertools = "0.10"
rand = "0.8"
